name: CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Insall Dependencies
        run: npm install
      - name: Generate Deployment Package
        run: zip -r todo-backend-build.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'todo-backend'
          environment_name: 'todo-backend-env'
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: todo-backend-build.zip
        
        
